global_costmap:
  global_frame: "map"
  robot_base_frame: "base_link"
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  rolling_window: false
  static_map: true

  footprint: [[0.2475, 0.150], [0.2475, -0.150], [-0.2475, -0.150], [-0.2475, 0.150]]
  footprint_padding: 0.05

  plugins:
    - {name: "static_map", type: "costmap_2d::StaticLayer"}
    - {name: "inflation_map", type: "costmap_2d::InflationLayer"}

  static_map:
    lethal_cost_threshold: 100
    map_topic: map
    first_map_only: true

  inflation_map:
    inflation_radius: 0.4
