base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"
controller_frequency: 5

GlobalPlanner:
  use_dijkstra: true
  default_tolerance: 0.0
  publish_potential: true
