joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate : 50
diff_drive:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ["bl_joint", "fl_joint"]
  right_wheel: ["br_joint", "fr_joint"]
  pose_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
  twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
  publish_rate: 50
  base_frame_id: "base_link"
  enable_odom_tf: true
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 1
      has_acceleration_limits: true
      max_acceleration: 5
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 3
      has_acceleration_limits: true
      max_acceleration: 5
